apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: minitelegram
data:
  DSN: "postgres://postgres:postgres@postgres:5432/minitelegram?sslmode=disable"
  REDIS_ADDR: "redis:6379"
  AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
  JWT_PRIVATE_KEY_PATH: "/secrets/es256.key"
  GIN_MODE: "release"
  PORT: "8080"
