apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
  namespace: minitelegram
type: Opaque
data:
  # This will be populated from your secrets/es256.key file
  # For now, we'll create it during deployment
  es256.key: ""
